title: EbMS Adapter
lang: en
description: EbMS adapter for Java

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme@v1.1.7

repository: eluinstra/ebms-admin

readme_index:
  with_frontmatter: true
